MusicApp/config/routes.rb
Rails.application.routes.draw do

	root to: 'bands#index'
	
  resource :session, only: [:new, :create, :destroy]

  resources :users, only: [:create, :new, :show]

  resources :bands do 
  	resources :albums, only: :new
  end
 
  resources :albums, except: [:index, :new] do
  	resources :tracks, only: :new
  end

  #solutions were misleading.
  #notes should be nested under tracks! (so that params stores track_id?)
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :create
  end

  resources :notes, only: :destroy

end

MusicApp/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  kind       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  album_name :string           not null
#

class Album < ActiveRecord::Base
	validates :band_id, :kind, :album_name, presence: true

	belongs_to :band
	has_many :tracks, dependent: :destroy

end

MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
	validates :name, presence: true

	has_many :albums, dependent: :destroy
	has_many :tracks, through: :albums, dependent: :destroy

end

MusicApp/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  track_id   :integer          not null
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ActiveRecord::Base
	validates :user_id, :track_id, presence: true

	belongs_to :user
	belongs_to :track
end

MusicApp/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  album_id   :integer          not null
#  kind       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  track_name :string           not null
#  lyrics     :text
#

class Track < ActiveRecord::Base
	validates :album_id, :track_name, :kind, presence: true

	belongs_to :album
	has_one :band, through: :album
	has_many :notes
	
end

MusicApp/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
	attr_reader :password

	validates :email, :password_digest, :session_token, presence: true
	validates :email, uniqueness: true
	before_validation :ensure_session_token

	has_many :notes

	def password=(password)
		@password = password
		self.password_digest = BCrypt::Password.create(password)
	end

	def is_password?(password)
		#had create and new backwards before!
		BCrypt::Password.new(self.password_digest).is_password?(password)
	end

	def reset_session_token!
		self.session_token = User.generate_session_token
		self.save!
		self.session_token
	end

	protected

		#need to rewrite as class method
		def self.generate_session_token
			SecureRandom.urlsafe_base64
		end

		def ensure_session_token
			#need to say User and not self here
			self.session_token ||= User.generate_session_token
		end

		def self.find_by_credentials(email, password)
			@user = User.find_by_email(email)
			return nil if @user.nil?
			@user.is_password?(password) ? @user : nil
		end

end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	before_action :require_login!
	
	def new
		@album = Album.new
		render :new_album
	end

	def create
		@album = Album.new(album_params)

		if @album.save
			redirect_to album_url(@album)
		else
			render :new_album
		end
	end

	def edit
		@album = Album.find(params[:id])
		render :edit_album
	end

	def update
		@album = Album.find(params[:id])

		if @album.update(album_params)
			redirect_to album_url(@album)
		else
			render :edit_album
		end
	end

	def show
		@album = Album.find(params[:id])
		render :show_album
	end

	def destroy
		@album = Album.find(params[:id])
		band_id = @album.band_id

		@album.destroy
		redirect_to band_url(band_id)
	end

	private

	def album_params
		params.require(:album).permit(:album_name, :band_id, :kind)
	end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def log_in!(user)
  # 	session_token = User.generate_session_token
		# user.session_token = session_token
		session[:session_token] = user.reset_session_token!
		redirect_to user_url(user)
	end

	def current_user
		user = User.find_by_session_token(session[:session_token])
		return nil if user.nil?
		user
		# find User by session_token
		# return user object or nil
	end

	def logged_in?
		# current_user.session_token == session[:session_token]
		# to make this a boolean value
		!!current_user
	end

	def require_login!
		redirect_to new_session_url unless logged_in?
	end

end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
	before_action :require_login!

	def index
		@bands = Band.all
		render :index_band
	end

	def new
		@band = Band.new
		render :new_band
	end

	def create
		@band = Band.new(band_params)

		if @band.save
			# fail
			redirect_to band_url(@band)
		else
			render :new_band
		end
	end

	def edit
		@band = Band.find(params[:id])
		render :edit_band
	end

	def update
		@band = Band.find(params[:id])

		if @band.update(band_params)
			redirect_to band_url(@band)
		else
			render :edit_band
		end
	end

	def show
		@band = Band.find(params[:id])
		render :show_band
	end

	def destroy
		@band = Band.find(params[:id])
		@band.destroy
		redirect_to bands_url
	end

	private

	def band_params
		params.require(:band).permit(:name)
	end

end

MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def new
	end

	def create
		@note = Note.new(note_params)
		@note.user_id = current_user.id
		@note.save
		redirect_to track_url(@note.track_id)
	end

	def destroy
		@note = Note.find(params[:id])
		@note.destroy
		redirect_to track_url(@note.track_id)
	end

	private

		def note_params
			#beware that hidden inputs in form also need to be permitted
			#track_id needs to be both here AND notes form partial!
			params.require(:note).permit(:body, :track_id)
		end

end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
		render :new
	end

	def create
		user = User.find_by_credentials(
			params[:user][:email],
			params[:user][:password]
			)

		if user.nil?
			flash[:errors] = 'Invalid username or password.'
			render :new
		else
			log_in!(user)
		end
	end

	def destroy
		current_user.reset_session_token!
		session[:session_token] = nil
		redirect_to new_session_url
	end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
	before_action :require_login!
	
	def new
		@track = Track.new
		render :new
	end

	def create
		@track = Track.new(track_params)

		if @track.save
			redirect_to track_url(@track)
		else
			render :new
		end
	end

	def edit
		@track = Track.find(params[:id])
		render :edit
	end

	def update
		@track = Track.find(params[:id])

		if @track.update(track_params)
			# fail
			redirect_to track_url(@track)
		else
			render :edit
		end
	end

	def show
		@track = Track.find(params[:id])
		render :show
	end

	def destroy
		@track = Track.find(params[:id])
		album_id = @track.album_id

		@track.destroy
		redirect_to album_url(album_id)
	end

	private

	def track_params
		#needed to add lyrics
		params.require(:track).permit(:track_name, :album_id, :kind, :lyrics)
	end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			log_in!(@user)
		else
			render :new
		end
	end

	def show
		@user = User.find(params[:id])
		render :show
	end

	private

		def user_params
			params.require(:user).permit(:email, :password)
		end

end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/notes_helper.rb
module NotesHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/views/shared/_create.html.erb
<%= link_to "Create track", new_album_track_url%>
<%= link_to "Create album", new_band_album_url%>
<%= link_to "Create band", new_band_url%>

MusicApp/app/views/tracks/_form.html.erb
<form action=<%= url %> method="post">
	<input type="hidden" name="_method" value=<%=http_verb%>>
	<input type='hidden'
	 name='authenticity token' 
	 value=<%=form_authenticity_token%>

<label> Album Name
	<select name="track[album_id]">
		<% Album.all.each do |album| %>
			<option 
				value= <%= album.id %>
				<%= @track.album_id == album.id ? "selected" : "" %>>
				<%= album.album_name %></option>
		<% end %>
	</select><br>
</label>

<label>Track Name
	<input 
		type="text" 
		name="track[track_name]" 
		value=<%=@track.track_name%>><br>
</label>

Track Type: 
<label>Regular
	<input type="radio" name="track[kind]" value="Regular"
	<%= @track.kind == "Regular" ? "checked" : ""%>>
</label>

<label>Bonus
	<input type="radio" name="track[kind]" value="Bonus"
	<%= @track.kind == "Bonus" ? "checked" : ""%>>
</label><br>

<label>Lyrics
<textarea 
	name="track[lyrics]" 
	rows="20" 
	cols="80"><%=@track.lyrics%></textarea>
</label>

<input type="submit" value=<%=msg%>>

</form>

MusicApp/app/views/tracks/edit.html.erb
<h1> Edit existing track </h1>

<%= render 'form', 
url: track_url(@track),
http_verb: "PATCH", 
msg: "Update" %>

MusicApp/app/views/tracks/new.html.erb
<h1> Create a new track </h1>

<%= render 'form', 
url: tracks_url, 
http_verb: "POST",
msg: "Create" %>

MusicApp/app/views/tracks/show.html.erb
<h1> Track page for <%= @track.track_name %> </h1>

<%= link_to "#{@track.album.album_name}", album_url(@track.album_id) %>

<ul>
	<li>Type of track <%= @track.kind.downcase %></li>
	<li>Name of the track: <%= @track.track_name %></li>
</ul>

Lyrics: <%= @track.lyrics %>
br><br><br>

Write a note!
<%= render 'notes/form', track: @track %>
<%= render 'notes/note', track: @track %>

<br><br>
<%= link_to "Edit track", edit_track_url%>
<%= button_to "Annihilate track", track_url, method: :delete%>
<br>


<ul>
<li><%= link_to "Create track", new_album_track_url(@track.album_id) %></li>
<li><%= link_to "Create album", new_band_album_url(@track.band.id) %></li>
<li><%= link_to "Create band", new_band_url%></li>
</ul>

MusicApp/app/views/users/new.html.erb
<h1> Sign up as a new user </h1>

<% @user.errors.full_messages.each do |msg| %>
	<%= msg %>
<% end %>

<form action=<%= users_url %> method="post">
	<input type='hidden'
	 name='authenticity token' 
	 value=<%=form_authenticity_token%>

	<label>Email
		<input type="text" name="user[email]">
	</label>

	<label>Password
		<input type="password" name="user[password]">
	</label>

<input type="Submit" value="Sign up!">

</form>

MusicApp/app/views/users/show.html.erb
<h1> Show page for <%= @user.email %> </h1>

<h3><%= link_to "All bands", bands_url %></h3>