AwesomeReddit/config/routes.rb
Rails.application.routes.draw do
	root to: 'subs#index'

  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: :destroy do
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :posts, except: :index do 
  	resources :comments, only: [:new]
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :comments, only: [:create, :destroy, :show]
end

AwesomeReddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#  session_token   :string(255)      not null
#

class User < ActiveRecord::Base  
  attr_reader :password
  
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 2, allow_nil: true }
  after_initialize :ensure_session_token
  
  has_many(
    :subs,
    class_name: "Sub",
    foreign_key: :moderator_id,
    inverse_of: :moderator
  )
  
  has_many :posts, inverse_of: :author
  has_many :comments, inverse_of: :user
  has_many :votes, inverse_of: :user
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new( self.password_digest ).is_password?(password)
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  protected
  
    def ensure_session_token
      self.session_token ||= User.generate_session_token
    end

end

AwesomeReddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  #this actually does the creation
  def create
    @user = User.new(user_params)
    
    if @user.save
      #take them to their show page
      login!(@user)
      #redirect to /users/123
      redirect_to user_url(@user)
    else
      #take the user back to new form
      render :new
    end
  end
  
  #this is /users/new, but fetches the form
  def new
    @user = User.new
    render :new
  end
  
  #this is /users/1
  def show
    @user = current_user
    render :show
  end

  #this is /users, done in haml!
  def index
    @users = User.all
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

AwesomeReddit/app/helpers/users_helper.rb
module UsersHelper
end

AwesomeReddit/app/views/users/index.html.haml
%h1 All the users

-@users.each do |user|
	%li=user.username

AwesomeReddit/app/views/users/new.html.erb
<h1>Sign up for 'Awesome' (not really) Reddit </h1>

<!-- We want to show username input, password, input, and sign up-->
<form action="<%= users_url %>" method="post">
  
  <input type="hidden" 
  name="authenticity_token" 
  value="<%=form_authenticity_token%>">
  
  <label>Username
    <input type="text" name="user[username]">
  </label><br>
  
  <label>Password
    <input type="password" name="user[password]">
  </label><br>
  
  <input type="Submit" value="Create user!">
  
</form>

AwesomeReddit/app/views/users/show.html.erb
<h1>Hi <%=@user.username%>! </h1>

<%= link_to "View all subs", subs_url %><br>
<%= link_to "Create a sub", new_sub_url %><br>
<!--work on personal subs  -->