AwesomeReddit/config/routes.rb
Rails.application.routes.draw do
	root to: 'subs#index'

  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: :destroy do
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :posts, except: :index do 
  	resources :comments, only: [:new]
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :comments, only: [:create, :destroy, :show]
end

AwesomeReddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime
#  updated_at   :datetime
#

class Sub < ActiveRecord::Base
  validates :title, :moderator_id, presence: true
  
  belongs_to(
    :moderator,
    class_name: "User",
    foreign_key: :moderator_id,
    primary_key: :id
  )
  
  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post

  has_many :votes, as: :votable, class_name: 'Vote'
  
end

AwesomeReddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  def index
    @subs = Sub.all
    render :index
  end
  
  def create
    @sub = current_user.subs.new(sub_params)
    
    #id not assigned until save
    if @sub.save
      redirect_to sub_url(@sub)
    else
      render :new
    end
  end
  
  def new
    @sub = Sub.new
    render :new
  end
  
  def show 
    @sub = Sub.find(params[:id])
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    
    if current_user.id == @sub.moderator_id
      render :edit
    else
      redirect_to sub_url(@sub)
    end
  end
  
  def update
    @sub = Sub.find(params[:id])
    
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
      # render :show
    else
      render :edit
    end
  end
  
  private
  
    def sub_params
      params.require(:sub).permit(:title, :description, :moderator_id)
    end
  
end

AwesomeReddit/app/helpers/subs_helper.rb
module SubsHelper
end

AwesomeReddit/app/views/subs/_sub_form.html.erb
<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= hidden_method %>">
  
  <input type="hidden" 
         name="authenticity_token" 
         value="<%= form_authenticity_token %>">
  
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title%>">
  </label><br>
  
  <label>Description
    <textarea name="sub[description]" rows="20" cols="80"><%= @sub.description%>
    </textarea>
  </label><br>
    
  <input type="Submit" value="<%= value %>">
  
</form>

AwesomeReddit/app/views/subs/edit.html.erb
<h1> Edit sub </h1>

<%= render 'sub_form',
    action: sub_url(@sub),
    hidden_method: 'PATCH',
    value: 'Update sub'
%>

AwesomeReddit/app/views/subs/index.html.erb
<h1>These are all the subs</h1>

<% @subs.each do |sub| %>
<%= link_to sub.title, sub_url(sub) %>
<br>
<% end %>

<br>
<br>
<%= link_to "Create a sub", new_sub_url %><br>

AwesomeReddit/app/views/subs/new.html.erb
<h1> Create sub </h1>

<%= render 'sub_form',
    action: subs_url,
    hidden_method: 'POST',
    value: 'Create sub'
%>

AwesomeReddit/app/views/subs/show.html.erb
<h1>Hello <%= current_user.username%></h1>
<h2><%= @sub.title %></h2>
<h3><%= @sub.description%></h3>

<ul>
	<% @sub.posts.each do |post| %>
		<li><%= link_to post.title, post_url(post) %></li>
	<% end %>
</ul>
<br>
<br>

<%= button_to 'Upvote', upvote_sub_url(@sub) %>
<%= button_to 'Downvote', downvote_sub_url(@sub) %>

<%= link_to "New post", new_post_url %><br>
<%= link_to("Edit sub", edit_sub_url) if current_user.id == @sub.moderator_id %><br>
<%= link_to "Back to all subs", subs_url %><br>
<!--work on posts -->

AwesomeReddit/app/views/subs/show.html.haml
<h1>Hello <%= current_user.username%></h1>
%h1 Hello =current_user.username

<h2><%= @sub.title %></h2>
<h3><%= @sub.description%></h3>

<ul>
	<% @sub.posts.each do |post| %>
		<li><%= link_to post.title, post_url(post) %></li>
	<% end %>
</ul>
<br>
<br>

<%= button_to 'Upvote', upvote_sub_url(@sub) %>
<%= button_to 'Downvote', downvote_sub_url(@sub) %>

<%= link_to "New post", new_post_url %><br>
<%= link_to("Edit sub", edit_sub_url) if current_user.id == @sub.moderator_id %><br>
<%= link_to "Back to all subs", subs_url %><br>
<!--work on posts -->