AwesomeReddit/config/routes.rb
Rails.application.routes.draw do
	root to: 'subs#index'

  resources :users, only: [:create, :new, :show, :index]
  resource :session, only: [:create, :new, :destroy]
  resources :subs, except: :destroy do
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :posts, except: :index do 
  	resources :comments, only: [:new]
  	member do
  		post "downvote"
  		post "upvote"
  	end
  end

  resources :comments, only: [:create, :destroy, :show]
end

AwesomeReddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  url        :string(255)
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :title, :author, presence: true
    
  belongs_to(
    :author,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub
  has_many :comments, inverse_of: :post

  has_many :votes, as: :votable, class_name: 'Vote'
  
  def parent_comments
    comments.where(parent_comment_id: nil)
  end

  def vote_count
    votes.sum(:value)
  end
end

AwesomeReddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController  
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post)
    else
      render :new_post
    end
  end
  
  def new
    @post = Post.new
  end
  
  def show 
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    
    if current_user.id == @post.user_id
      render :edit
    else
      redirect_to sub_post_url(@post)
    end
  end
  
  def update
    @post = Post.find(params[:id])
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit_post
    end
  end

  def downvote; vote(-1); end
  def upvote; vote(1); end
  
  private
    def post_params
      params.require(:post).permit(
        :title, :url, :content, :user_id, sub_ids: []
      )
    end

    # custom action!
    def vote(direction)
      @post = Post.find(params[:id])
      criteria = { user_id: current_user.id,
                   votable_id: @post.id, 
                   votable_type: "Post" }
      @vote = Vote.find_by(criteria)

      if @vote
        @vote.update(value: direction)
      else
        criteria[:value] = direction
        @post.votes.create!(criteria)
      end

      redirect_to post_url(@post)
    end
end

AwesomeReddit/app/helpers/posts_helper.rb
module PostsHelper
end

AwesomeReddit/app/views/posts/_form.html.erb
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= hidden_method %>">
  
  <input type="hidden" 
         name="authenticity_token" 
         value="<%=form_authenticity_token%>">
  
  <label>Title
    <input type="text" name="post[title]" value='<%= post.title %>'>
  </label><br>
  
  <label>Link
    <input type="text" name="post[url]" value='<%= post.url %>'>
  </label><br>
  
  <label>Content
    <textarea name="post[content]" rows="20" cols="80"><%= post.content %>
    </textarea>
  </label><br>

  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type='checkbox' 
             name='post[sub_ids][]' 
             value='<%= sub.id %>'
             <%= "checked" if post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
    
  <br><br><input type="Submit" value="<%= value %>">
</form>

AwesomeReddit/app/views/posts/edit.html.erb
<h1> Edit post </h1>

<%= render 'form',
    action: post_url(@post),
    hidden_method: 'PATCH',
    post: @post,
    value: 'Update post'
%>

AwesomeReddit/app/views/posts/edit_post.html.erb
<h1> Edit post </h1>

<%= render 'form',
    action: post_url(@post),
    hidden_method: 'PATCH',
    post: @post,
    value: 'Update post'
%>

AwesomeReddit/app/views/posts/new.html.erb
<!-- allow user to select multiple subs via checkboxes -->
<h1> Create post </h1>

<%= render 'form',
    action: posts_url,
    hidden_method: 'POST',
    post: @post,
    value: 'Create post'
%>

AwesomeReddit/app/views/posts/new_post.html.erb
<!-- allow user to select multiple subs via checkboxes -->
<h1> Create post </h1>

<%= render 'form',
    action: posts_url,
    hidden_method: 'POST',
    post: @post,
    value: 'Create post'
%>

AwesomeReddit/app/views/posts/show.html.erb
<h2>Hello <%= current_user.username %></h2>

<h3><%="#{@post.title} (#{@post.vote_count})"%></h3>

<%= button_to 'Upvote', upvote_post_url(@post) %>
<%= button_to 'Downvote', downvote_post_url(@post) %>

<% if @post.url!='none' %>
	<a href='<%= @post.url %>'>More info</a> <br>
<% end %>

<%= @post.content %>
<br><br>

This post is on these subs:
<% @post.subs.each do |sub| %>
	&nbsp;<%= link_to sub.title, sub_url(sub) %><br>
<% end %>

<br>
<%= link_to("Edit post", edit_post_url) if current_user.id == @post.user_id %><br>

<br>
<% @post.parent_comments.each do |comment| %>
	<span style='font-family: verdana;'>
		<%= "#{comment.user.username} says: #{comment.body}" %>
		<%= link_to '...', comment_url(comment) %>
		<br>
	</span>
<% end %>

<span style='font-weight: bold;'>
	<br>
	<%= link_to 'Leave a comment', new_post_comment_url(@post) %>
</span>

AwesomeReddit/app/views/posts/show_post.html.erb
<h2>Hello <%= current_user.username %></h2>

<h3><%="#{@post.title} (#{@post.vote_count})"%></h3>

<%= button_to 'Upvote', upvote_post_url(@post) %>
<%= button_to 'Downvote', downvote_post_url(@post) %>

<% if @post.url!='none' %>
	<a href='<%= @post.url %>'>More info</a> <br>
<% end %>

<%= @post.content %>
<br><br>

This post is on these subs:
<% @post.subs.each do |sub| %>
	&nbsp;<%= link_to sub.title, sub_url(sub) %><br>
<% end %>

<br>
<%= link_to("Edit post", edit_post_url) if current_user.id == @post.user_id %><br>

<br>
<% @post.parent_comments.each do |comment| %>
	<span style='font-family: verdana;'>
		<%= "#{comment.user.username} says: #{comment.body}" %>
		<%= link_to '...', comment_url(comment) %>
		<br>
	</span>
<% end %>

<span style='font-weight: bold;'>
	<br>
	<%= link_to 'Leave a comment', new_post_comment_url(@post) %>
</span>